version: '3.5'

services:

  products:
    build:
      context: ./services/products
      dockerfile: Dockerfile-prod
    expose:
      - 5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.ProductionConfig
      - DATABASE_URL=postgres://postgres:postgres@products-db:5432/celular_prod
      - DATABASE_TEST_URL=postgres://postgres:postgres@products-db:5432/celular_test
    depends_on:  # <-- nuevo
      - products-db

  products-db:  # <-- nuevo
    build:
      context: ./services/products/project/db
      dockerfile: Dockerfile
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-prod
    restart: always
    ports:
      - 80:80
    depends_on:
      - products
      - client

  client:
    container_name: client
    build:
      context: ./services/client
      dockerfile: Dockerfile-prod
      args:
        - NODE_ENV=production
        - REACT_APP_PRODUCTS_SERVICE_URL=${REACT_APP_PRODUCTS_SERVICE_URL}
    ports:
      - '3007:80'
    depends_on:
      - products
